version: "3.7"

services: 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      discovery.type: single-node
      #xpack.graph.enabled: "false"
      #xpack.monitoring.enabled: "true"
      #xpack.security.enabled: "false"
      #xpack.watcher.enabled: "false"
    ports:
      - "9200:9200"
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.4.0
    environment:
      #xpack.monitoring.enabled: "true"
      xpack.monitoring.elasticsearch.hosts: http://192.168.0.102:9200
    volumes:
      - ./logstash/pipeline/kafka.conf:/usr/share/logstash/pipeline/kafka.conf:ro
    ports:
      - "5046:5046"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      #xpack.graph.enabled: "false"
      #xpack.monitoring.enabled: "true"
      #xpack.reporting.enabled: "false"
      #xpack.security.enabled: "false"
      elasticsearch.hosts: http://192.168.0.102:9200
    ports: 
      - "5601:5601"
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.4.0
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
