version: "3.7"

services: 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      discovery.type: single-node
      xpack.graph.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.security.enabled: "false"
      xpack.watcher.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.4.0
    environment:
      xpack.monitoring.enabled: "false"
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
  kibana:
    container_name: kibana
    environment:
      xpack.graph.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.reporting.enabled: "false"
      xpack.security.enabled: "false"
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports: 
      - "5601:5601"
