version: "3.7"

services: 
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx1g -Xms1g
    ports:
      - "9200:9200"
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.4.0
    environment:
      LS_JAVA_OPTS: -Xmx1g -Xms1g
    volumes:
      - ./logstash/pipeline/kafka.conf:/usr/share/logstash/pipeline/kafka.conf:ro
    ports:
      - "5046:5046"
      - 12201:12201/udp
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports: 
      - "5601:5601"
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.4.0
    user: root
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
  httpd:
    image: httpd:latest
    depends_on:
      - logstash
    ports:
      - 80:80
    logging:
      driver: gelf
      options:
        gelf-address: "udp://10.69.0.50:12201"
